# Generated by Django 4.2 on 2025-12-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('K', 'Doniyor'), ('D', 'D')], max_length=1),
        ),
    ]
